services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myprojectdb
      POSTGRES_USER: derek
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro  #  Nginx configuration file location
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Path for accessing Let's Encrypt SSL Certs for HTTPS
      - /etc/nginx/ssl:/etc/nginx/ssl:ro  # Path to Diffie-Hellman Key Exchange Enc.
      - ./frontend/dist:/usr/share/nginx/html  # Frontend file location to serve with NGINX
    depends_on:
      - backend

volumes:
  postgres_data: