# Generated by Django 5.0.3 on 2024-03-05 00:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EncryptedFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("key", models.BinaryField()),
                ("iv", models.BinaryField()),
            ],
        ),
    ]
